# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688bda2af5a53678c018bba05a63280a651b3e7e6f4a87454b602a4970c9cd800f30a42aa1d91bacbe4455a3755ce5c231acecc3559fa37cd8ffe7a3c22392f8

test:
  secret_key_base: b03d89bd86f0e5cc79fa18be1f98ab4719b50f12740eb0bc57cdb2ecb7ff608e83c5f91c33ac4213c62ef90e7b7d40746a13c1dc7747f7c398ce818ffaa84eeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
